language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install:
- npm install
script:
- npm run build
addons:
  ssh_known_hosts:
  - "$DEPLOY_HOST"
before_install:
- openssl aes-256-cbc -K $encrypted_e2110b668d31_key -iv $encrypted_e2110b668d31_iv
  -in id_rsa_tencent.enc -out ~\/.ssh/id_rsa_tencent -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh "$DEPLOY_USER"@"$DEPLOY_HOST" -o StrictHostKeyChecking=no 'cd ~/cube-practise && git pull && npm install && npm run build'

